package com.jmr.batch.processor.instruments;

import org.springframework.batch.item.ItemProcessor;
import org.springframework.stereotype.Component;

import com.jmr.batch.entity.instruments.TransIstmInstrTxn;
import com.jmr.batch.entity.instruments.TransIstmInstrTxnPK;
import com.jmr.batch.model.instruments.TransIstmInstrTxnModel;
import com.jmr.framework.util.JMRDateUtil;
import com.jmr.framework.util.JMRUtil;

@Component
public class FirstItemProIstmInstrTxn implements ItemProcessor<TransIstmInstrTxnModel, TransIstmInstrTxn> {

	@Override

	public TransIstmInstrTxn process(TransIstmInstrTxnModel item) throws Exception {
		TransIstmInstrTxn transIstmInstrTxn = new TransIstmInstrTxn();
		transIstmInstrTxn.setPayableBranch(item.getPayable_branch());
		transIstmInstrTxn.setChgGl(item.getChg_gl());
		transIstmInstrTxn.setChgCcy(item.getChg_ccy());
		transIstmInstrTxn.setMisHead1(item.getMis_head_1());
		transIstmInstrTxn.setChgGl1(item.getChg_gl_1());
		transIstmInstrTxn.setChgCcy1(item.getChg_ccy_1());
		transIstmInstrTxn.setMisHead2(item.getMis_head_2());
		transIstmInstrTxn.setChgGl2(item.getChg_gl_2());
		transIstmInstrTxn.setChgCcy2(item.getChg_ccy_2());
		transIstmInstrTxn.setMisHead3(item.getMis_head_3());
		transIstmInstrTxn.setChgGl3(item.getChg_gl_3());
		transIstmInstrTxn.setChgCcy3(item.getChg_ccy_3());
		transIstmInstrTxn.setMisHead4(item.getMis_head_4());
		transIstmInstrTxn.setChgGl4(item.getChg_gl_4());
		transIstmInstrTxn.setChgCcy4(item.getChg_ccy_4());
		transIstmInstrTxn.setMisHead5(item.getMis_head_5());
		transIstmInstrTxn.setBenCust(item.getBen_cust());
		transIstmInstrTxn.setIssuerCode(item.getIssuer_code());
		transIstmInstrTxn.setPayableBank(item.getPayable_bank());
		transIstmInstrTxn.setProductCode(item.getProduct_code());
		transIstmInstrTxn.setInstrStat(item.getInstr_stat());
		transIstmInstrTxn.setBatchNo(item.getBatch_no());
		transIstmInstrTxn.setIssueBank(item.getIssue_bank());
		transIstmInstrTxn.setManualInput(item.getManual_input());
		transIstmInstrTxn.setUiAcNo(item.getUi_ac_no());
		transIstmInstrTxn.setTestkey(item.getTestkey());
		transIstmInstrTxn.setBenefPhNo(item.getBenef_ph_no());
		transIstmInstrTxn.setBenefIdNo(item.getBenef_id_no());
		transIstmInstrTxn.setRemName(item.getRem_name());
		transIstmInstrTxn.setRemPhNo(item.getRem_ph_no());
		transIstmInstrTxn.setRemIdNo(item.getRem_id_no());
		transIstmInstrTxn.setInwardTtRef(item.getInward_tt_ref());
		transIstmInstrTxn.setIssuingBranch(item.getIssuing_branch());
		transIstmInstrTxn.setInstrCcy(item.getInstr_ccy());
		transIstmInstrTxn.setAcBranch(item.getAc_branch());
		transIstmInstrTxn.setAcCcy(item.getAc_ccy());
		transIstmInstrTxn.setTxnCode(item.getTxn_code());
		transIstmInstrTxn.setTxnCode1(item.getTxn_code_1());
		transIstmInstrTxn.setTxnCode2(item.getTxn_code_2());
		transIstmInstrTxn.setTxnCode3(item.getTxn_code_3());
		transIstmInstrTxn.setTxnCode4(item.getTxn_code_4());
		transIstmInstrTxn.setOfsCcy(item.getOfs_ccy());
		transIstmInstrTxn.setOfsBranch(item.getOfs_branch());
		transIstmInstrTxn.setBenCcy(item.getBen_ccy());
		transIstmInstrTxn.setCountryCode(item.getCountry_code());
		transIstmInstrTxn.setChargeCcy(item.getCharge_ccy());
		transIstmInstrTxn.setChargeAccBrn(item.getCharge_acc_brn());
		transIstmInstrTxn.setRemarks(item.getRemarks());
		transIstmInstrTxn.setNarrative(item.getNarrative());
		transIstmInstrTxn.setReissueRemarks(item.getReissue_remarks());
		transIstmInstrTxn.setChgDesc(item.getChg_desc());
		transIstmInstrTxn.setChgDesc1(item.getChg_desc1());
		transIstmInstrTxn.setChgDesc2(item.getChg_desc2());
		transIstmInstrTxn.setChgDesc3(item.getChg_desc3());
		transIstmInstrTxn.setChgDesc4(item.getChg_desc4());
		transIstmInstrTxn.setAcNo(item.getAc_no());
		transIstmInstrTxn.setChargeAccount(item.getCharge_account());
		transIstmInstrTxn.setOfsAcc(item.getOfs_acc());
		transIstmInstrTxn.setBenAccount(item.getBen_account());
		transIstmInstrTxn.setTheirAcc(item.getTheir_acc());
		transIstmInstrTxn.setTheirAcc1(item.getTheir_acc1());
		transIstmInstrTxn.setTheirAcc2(item.getTheir_acc2());
		transIstmInstrTxn.setTheirAcc3(item.getTheir_acc3());
		transIstmInstrTxn.setTheirAcc4(item.getTheir_acc4());
		transIstmInstrTxn.setMultiRefNo(item.getMulti_ref_no());
		transIstmInstrTxn.setUiChargeAccount(item.getUi_charge_account());
		transIstmInstrTxn.setInstrType(item.getInstr_type());
		transIstmInstrTxn.setInstrNo(item.getInstr_no());
		transIstmInstrTxn.setDdMicrNo(item.getDd_micr_no());
		transIstmInstrTxn.setOrgDraftNo(item.getOrg_draft_no());
		transIstmInstrTxn.setReissuedDraftNo(item.getReissued_draft_no());
		transIstmInstrTxn.setScode(item.getScode());
		transIstmInstrTxn.setXref(item.getXref());
		transIstmInstrTxn.setChequeNo(item.getCheque_no());
		transIstmInstrTxn.setOldDdMicrNo(item.getOld_dd_micr_no());
		transIstmInstrTxn.setOldInstrNo(item.getOld_instr_no());
		transIstmInstrTxn.setMakerId(item.getMaker_id());
		transIstmInstrTxn.setCheckerId(item.getChecker_id());
		transIstmInstrTxn.setSsn(item.getSsn());
		transIstmInstrTxn.setRelCustomer(item.getRel_customer());
		transIstmInstrTxn.setBenefName(item.getBenef_name());
		transIstmInstrTxn.setBenefAddr1(item.getBenef_addr_1());
		transIstmInstrTxn.setBenefAddr2(item.getBenef_addr_2());
		transIstmInstrTxn.setBenefAddr3(item.getBenef_addr_3());
		transIstmInstrTxn.setBenefAddr4(item.getBenef_addr_4());
		transIstmInstrTxn.setBenefAddr5(item.getBenef_addr_5());
		transIstmInstrTxn.setIdentifierName1(item.getIdentifier_name_1());
		transIstmInstrTxn.setIdentifierValue1(item.getIdentifier_value_1());
		transIstmInstrTxn.setIdentifierName2(item.getIdentifier_name_2());
		transIstmInstrTxn.setIdentifierValue2(item.getIdentifier_value_2());
		transIstmInstrTxn.setIdentifierName3(item.getIdentifier_name_3());
		transIstmInstrTxn.setIdentifierValue3(item.getIdentifier_value_3());
		transIstmInstrTxn.setIdentifierName4(item.getIdentifier_name_4());
		transIstmInstrTxn.setIdentifierValue4(item.getIdentifier_value_4());
		transIstmInstrTxn.setIdentifierName5(item.getIdentifier_name_5());
		transIstmInstrTxn.setIdentifierValue5(item.getIdentifier_value_5());
		transIstmInstrTxn.setIdentifierName6(item.getIdentifier_name_6());
		transIstmInstrTxn.setIdentifierValue6(item.getIdentifier_value_6());
		transIstmInstrTxn.setDeliveryAdd1(item.getDelivery_add1());
		transIstmInstrTxn.setDeliveryAdd2(item.getDelivery_add2());
		transIstmInstrTxn.setDeliveryAdd3(item.getDelivery_add3());
		transIstmInstrTxn.setDeliveryAdd4(item.getDelivery_add4());
		transIstmInstrTxn.setRemAddr1(item.getRem_addr_1());
		transIstmInstrTxn.setRemAddr2(item.getRem_addr_2());
		transIstmInstrTxn.setRemAddr3(item.getRem_addr_3());
		transIstmInstrTxn.setRemAddr4(item.getRem_addr_4());
		transIstmInstrTxn.setRecordStat(item.getRecord_stat());
		transIstmInstrTxn.setAuthStat(item.getAuth_stat());
		transIstmInstrTxn.setOnceAuth(item.getOnce_auth());
		transIstmInstrTxn.setNettingInd(item.getNetting_ind());
		transIstmInstrTxn.setNettingInd1(item.getNetting_ind_1());
		transIstmInstrTxn.setNettingInd2(item.getNetting_ind_2());
		transIstmInstrTxn.setNettingInd3(item.getNetting_ind_3());
		transIstmInstrTxn.setNettingInd4(item.getNetting_ind_4());
		transIstmInstrTxn.setPrintCopy(item.getPrint_copy());
		transIstmInstrTxn.setReissued(item.getReissued());
		transIstmInstrTxn.setChgType(item.getChg_type());
		transIstmInstrTxn.setChgType1(item.getChg_type1());
		transIstmInstrTxn.setChgType2(item.getChg_type2());
		transIstmInstrTxn.setChgType3(item.getChg_type3());
		transIstmInstrTxn.setChgType4(item.getChg_type4());
		transIstmInstrTxn.setWaiver(item.getWaiver());
		transIstmInstrTxn.setWaiver1(item.getWaiver1());
		transIstmInstrTxn.setWaiver2(item.getWaiver2());
		transIstmInstrTxn.setWaiver3(item.getWaiver3());
		transIstmInstrTxn.setWaiver4(item.getWaiver4());
		transIstmInstrTxn.setDeliveryMode(item.getDelivery_mode());
		transIstmInstrTxn.setPaymentMode(item.getPayment_mode());
		transIstmInstrTxn.setRevalidated(item.getRevalidated());
		transIstmInstrTxn.setDuplicate(item.getDuplicate());
		transIstmInstrTxn.setTtPaymentType(item.getTt_payment_type());
		transIstmInstrTxn.setChgByCash(item.getChg_by_cash());
		transIstmInstrTxn.setChgMode(item.getChg_mode());
		transIstmInstrTxn.setPrintStat(item.getPrint_stat());
		transIstmInstrTxn.setTxnTanked(item.getTxn_tanked());
		transIstmInstrTxn.setIsPrinted(item.getIs_printed());
		if(!JMRUtil.isNullOrEmpty(item.getEvent_seq_no())){transIstmInstrTxn.setEventSeqNo(Double.valueOf(item.getEvent_seq_no()));}
		if(!JMRUtil.isNullOrEmpty(item.getInstr_amount())){transIstmInstrTxn.setInstrAmount(Double.valueOf(item.getInstr_amount()));}
		if(!JMRUtil.isNullOrEmpty(item.getExch_rate())){transIstmInstrTxn.setExchRate(Double.valueOf(item.getExch_rate()));}
		if(!JMRUtil.isNullOrEmpty(item.getAcy_amount())){transIstmInstrTxn.setAcyAmount(Double.valueOf(item.getAcy_amount()));}
		if(!JMRUtil.isNullOrEmpty(item.getLcy_amount())){transIstmInstrTxn.setLcyAmount(Double.valueOf(item.getLcy_amount()));}
		if(!JMRUtil.isNullOrEmpty(item.getMod_no())){transIstmInstrTxn.setModNo(Double.valueOf(item.getMod_no()));}
		if(!JMRUtil.isNullOrEmpty(item.getChg_amt())){transIstmInstrTxn.setChgAmt(Double.valueOf(item.getChg_amt()));}
		if(!JMRUtil.isNullOrEmpty(item.getChg_in_acy())){transIstmInstrTxn.setChgInAcy(Double.valueOf(item.getChg_in_acy()));}
		if(!JMRUtil.isNullOrEmpty(item.getChg_in_lcy())){transIstmInstrTxn.setChgInLcy(Double.valueOf(item.getChg_in_lcy()));}
		if(!JMRUtil.isNullOrEmpty(item.getChg_ccy_acy_rate())){transIstmInstrTxn.setChgCcyAcyRate(Double.valueOf(item.getChg_ccy_acy_rate()));}
		if(!JMRUtil.isNullOrEmpty(item.getAcy_lcy_rate())){transIstmInstrTxn.setAcyLcyRate(Double.valueOf(item.getAcy_lcy_rate()));}
		if(!JMRUtil.isNullOrEmpty(item.getChg_amt_1())){transIstmInstrTxn.setChgAmt1(Double.valueOf(item.getChg_amt_1()));}
		if(!JMRUtil.isNullOrEmpty(item.getChg_in_acy_1())){transIstmInstrTxn.setChgInAcy1(Double.valueOf(item.getChg_in_acy_1()));}
		if(!JMRUtil.isNullOrEmpty(item.getChg_in_lcy_1())){transIstmInstrTxn.setChgInLcy1(Double.valueOf(item.getChg_in_lcy_1()));}
		if(!JMRUtil.isNullOrEmpty(item.getChg_ccy_acy_rate_1())){transIstmInstrTxn.setChgCcyAcyRate1(Double.valueOf(item.getChg_ccy_acy_rate_1()));}
		if(!JMRUtil.isNullOrEmpty(item.getAcy_lcy_rate_1())){transIstmInstrTxn.setAcyLcyRate1(Double.valueOf(item.getAcy_lcy_rate_1()));}
		if(!JMRUtil.isNullOrEmpty(item.getChg_amt_2())){transIstmInstrTxn.setChgAmt2(Double.valueOf(item.getChg_amt_2()));}
		if(!JMRUtil.isNullOrEmpty(item.getChg_in_acy_2())){transIstmInstrTxn.setChgInAcy2(Double.valueOf(item.getChg_in_acy_2()));}
		if(!JMRUtil.isNullOrEmpty(item.getChg_in_lcy_2())){transIstmInstrTxn.setChgInLcy2(Double.valueOf(item.getChg_in_lcy_2()));}
		if(!JMRUtil.isNullOrEmpty(item.getChg_ccy_acy_rate_2())){transIstmInstrTxn.setChgCcyAcyRate2(Double.valueOf(item.getChg_ccy_acy_rate_2()));}
		if(!JMRUtil.isNullOrEmpty(item.getAcy_lcy_rate_2())){transIstmInstrTxn.setAcyLcyRate2(Double.valueOf(item.getAcy_lcy_rate_2()));}
		if(!JMRUtil.isNullOrEmpty(item.getChg_amt_3())){transIstmInstrTxn.setChgAmt3(Double.valueOf(item.getChg_amt_3()));}
		if(!JMRUtil.isNullOrEmpty(item.getChg_in_acy_3())){transIstmInstrTxn.setChgInAcy3(Double.valueOf(item.getChg_in_acy_3()));}
		if(!JMRUtil.isNullOrEmpty(item.getChg_in_lcy_3())){transIstmInstrTxn.setChgInLcy3(Double.valueOf(item.getChg_in_lcy_3()));}
		if(!JMRUtil.isNullOrEmpty(item.getChg_ccy_acy_rate_3())){transIstmInstrTxn.setChgCcyAcyRate3(Double.valueOf(item.getChg_ccy_acy_rate_3()));}
		if(!JMRUtil.isNullOrEmpty(item.getAcy_lcy_rate_3())){transIstmInstrTxn.setAcyLcyRate3(Double.valueOf(item.getAcy_lcy_rate_3()));}
		if(!JMRUtil.isNullOrEmpty(item.getChg_amt_4())){transIstmInstrTxn.setChgAmt4(Double.valueOf(item.getChg_amt_4()));}
		if(!JMRUtil.isNullOrEmpty(item.getChg_in_acy_4())){transIstmInstrTxn.setChgInAcy4(Double.valueOf(item.getChg_in_acy_4()));}
		if(!JMRUtil.isNullOrEmpty(item.getChg_in_lcy_4())){transIstmInstrTxn.setChgInLcy4(Double.valueOf(item.getChg_in_lcy_4()));}
		if(!JMRUtil.isNullOrEmpty(item.getChg_ccy_acy_rate_4())){transIstmInstrTxn.setChgCcyAcyRate4(Double.valueOf(item.getChg_ccy_acy_rate_4()));}
		if(!JMRUtil.isNullOrEmpty(item.getAcy_lcy_rate_4())){transIstmInstrTxn.setAcyLcyRate4(Double.valueOf(item.getAcy_lcy_rate_4()));}
		if(!JMRUtil.isNullOrEmpty(item.getOfs_amount())){transIstmInstrTxn.setOfsAmount(Double.valueOf(item.getOfs_amount()));}
		if(!JMRUtil.isNullOrEmpty(item.getDiscount_days())){transIstmInstrTxn.setDiscountDays(Double.valueOf(item.getDiscount_days()));}
		if(!JMRUtil.isNullOrEmpty(item.getPayout_chg())){transIstmInstrTxn.setPayoutChg(Double.valueOf(item.getPayout_chg()));}
		if(!JMRUtil.isNullOrEmpty(item.getLcy_chg_exch_rate())){transIstmInstrTxn.setLcyChgExchRate(Double.valueOf(item.getLcy_chg_exch_rate()));}
		if(!JMRUtil.isNullOrEmpty(item.getLcy_chg_exch_rate1())){transIstmInstrTxn.setLcyChgExchRate1(Double.valueOf(item.getLcy_chg_exch_rate1()));}
		if(!JMRUtil.isNullOrEmpty(item.getLcy_chg_exch_rate2())){transIstmInstrTxn.setLcyChgExchRate2(Double.valueOf(item.getLcy_chg_exch_rate2()));}
		if(!JMRUtil.isNullOrEmpty(item.getLcy_chg_exch_rate3())){transIstmInstrTxn.setLcyChgExchRate3(Double.valueOf(item.getLcy_chg_exch_rate3()));}
		if(!JMRUtil.isNullOrEmpty(item.getLcy_chg_exch_rate4())){transIstmInstrTxn.setLcyChgExchRate4(Double.valueOf(item.getLcy_chg_exch_rate4()));}
		if(!JMRUtil.isNullOrEmpty(item.getReval_freq_days())){transIstmInstrTxn.setRevalFreqDays(Double.valueOf(item.getReval_freq_days()));}
		if(!JMRUtil.isNullOrEmpty(item.getReval_freq_months())){transIstmInstrTxn.setRevalFreqMonths(Double.valueOf(item.getReval_freq_months()));}
		if(!JMRUtil.isNullOrEmpty(item.getReval_freq_years())){transIstmInstrTxn.setRevalFreqYears(Double.valueOf(item.getReval_freq_years()));}
		if(!JMRUtil.isNullOrEmpty(item.getInstr_date())){transIstmInstrTxn.setInstrDate(JMRDateUtil.getDateFromString(item.getInstr_date(),JMRDateUtil.DATE_FORMATMMddyyyy));}
		if(!JMRUtil.isNullOrEmpty(item.getMaker_dt_stamp())){transIstmInstrTxn.setMakerDtStamp(JMRDateUtil.getDateFromString(item.getMaker_dt_stamp(),JMRDateUtil.DATE_FORMATMMddyyyy));}
		if(!JMRUtil.isNullOrEmpty(item.getChecker_dt_stamp())){transIstmInstrTxn.setCheckerDtStamp(JMRDateUtil.getDateFromString(item.getChecker_dt_stamp(),JMRDateUtil.DATE_FORMATMMddyyyy));}
		if(!JMRUtil.isNullOrEmpty(item.getExpiry_date())){transIstmInstrTxn.setExpiryDate(JMRDateUtil.getDateFromString(item.getExpiry_date(),JMRDateUtil.DATE_FORMATMMddyyyy));}
		if(!JMRUtil.isNullOrEmpty(item.getTrn_dt())){transIstmInstrTxn.setTrnDt(JMRDateUtil.getDateFromString(item.getTrn_dt(),JMRDateUtil.DATE_FORMATMMddyyyy));}
		if(!JMRUtil.isNullOrEmpty(item.getCheque_issue_date())){transIstmInstrTxn.setChequeIssueDate(JMRDateUtil.getDateFromString(item.getCheque_issue_date(),JMRDateUtil.DATE_FORMATMMddyyyy));}

		TransIstmInstrTxnPK transIstmInstrTxnPK = new TransIstmInstrTxnPK();
		transIstmInstrTxnPK.setVersionNo(item.getVersion_no());
		transIstmInstrTxnPK.setContractRefNo(item.getContract_ref_no());
		transIstmInstrTxn.setId(transIstmInstrTxnPK);
	
		return transIstmInstrTxn;
	}
	}